import {
  LogoutLink,
  LoginLink,
  RegisterLink,
  getKindeServerSession,
} from "@kinde-oss/kinde-auth-nextjs/server";
import "./globals.css";
import NextLink from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isAuthenticated, getUser } = getKindeServerSession();
  const user = getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 flex justify-between">
          <h1 className="font-medium">Kinde App</h1>
          {isAuthenticated() ? (
            <div>
              <LogoutLink className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Logout
              </LogoutLink>
            </div>
          ) : (
            <div>
              <LoginLink className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-3">
                Sign in
              </LoginLink>
              <NextLink
                href={"/api/auth/login"}
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-3"
              >
                Sign in
              </NextLink>
              <RegisterLink
                orgCode="org_7e6add41413"
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              >
                Sign up
              </RegisterLink>
            </div>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
